# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - foxnivalApiDemo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Spring Gradle Build Action
      uses: spring-io/spring-gradle-build-action@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: actions/checkout@v3
    - uses: spring-io/spring-gradle-build-action@v2
    - name: Run build
      run: ./gradlew clean build
    
          
